spring.application.name=openjfs
spring.mvc.pathmatch.matching-strategy=path_pattern_parser
server.port=${OPENJFS_PORT:8080}
server.forward-headers-strategy=framework
server.undertow.threads.worker=${OPENJFS_WORKER_THREADS:200}
openjfs.data-path=${OPENJFS_DATA_PATH:${user.dir}}
openjfs.allow-hidden=${OPENJFS_ALLOW_HIDDEN:false}
openjfs.allow-zip-directories=${OPENJFS_ALLOW_ZIP_DIRECTORIES:true}
openjfs.zip-compression-level=${OPENJFS_ZIP_COMPRESSION_LEVEL:1}
openjfs.search-max-results=${OPENJFS_SEARCH_MAX_RESULTS:1000}
openjfs.server-name=${OPENJFS_SERVER_NAME:openjfs}
